# Send-MailMessage -SmtpServer 'smtp.server.local' -From aayush1312@live.com -To metalmitila@gmail.com -Subject 'this is a subject' -Body 'this is the body' -Attachments 'C:\Users\Aayush\Desktop\Job Bewerbung\sell.sh'
# Send-MailMessage -From me@company.org -To joe@gmail.com -Subject 'this is a subject' -Body 'this is the body' -Attachments 'C:\file.doc'
# $gmailCred = Get-Credential

# $sendMailParams = @{
#     From = 'aayush1312@live.com' ## Must be gmail.com
#     To = 'metalmitila@gmail.com'
#     Subject = 'some subject'
#     Body = 'some body'
#     SMTPServer = 'smtp.server.local'
#     Port = 587
#     UseSsl = $true
#     Attachments = 'C:\Users\Aayush\Desktop\Job Bewerbung\sell.sh'
#     Credential = $gmailCred

# }

# Send-MailMessage @sendMailParams

#Get an Outlook application object

$toEmail = $args[0]
$anrede = $args[2]
$jobTitle = $args[3]
$toEmail

$o = New-Object -com Outlook.Application
 
$mail = $o.CreateItem(0)
 
#2 = High importance message
# $mail.importance = 2
$mail.subject = $args[1] 

$mail.body = "$anrede, 

hiermit bewerbe ich mich fuer die von Ihnen angebotene Stelle als $jobTitle.

Im Anhang zu dieser E-Mail finden Sie meine Bewerbungsunterlagen.

Fuer Rueckfragen stehe ich Ihnen gerne zur Verfuegung. 

Mit freundlichen Gruessen,
Aayush Yadav"# "This is the subject of the mail"
# $mail.body = $args[2] # "This is the body of the email. It has been automatically generated by a script."
 
Write-Output $args[1] 
Write-Output $mail.body 
#separate multiple recipients with a ";"
$mail.To = $toEmail #'metalmitila@gmail.com'
#$mail.CC = <OTHER RECIPIENT 1>;<OTHER RECIPIENT 2>
Write-Output $args[4]
# Add Attachment
if($args[4].equals("Software")){
    $mail.Attachments.Add('C:\Users\Aayush\Desktop\Job Bewerbung\BewerbungsMappe.pdf');
    $mail.Send()
    Write-Output "Email Sent Software"

}
elseif( $args[4].equals("Elektro")) {
    $mail.Attachments.Add('C:\Users\Aayush\Desktop\Job Bewerbung\E_BewerbungsMappe.pdf');
    $mail.Send()
    Write-Output "Email Sent Elektro"

}
else {
    Write-Output "Email not Sent"
}
 
# $mail.Send()
# Write-Output "Email Sent"
